version: "3.8"
services:
  backend:
    image: "ksaikishore/spring-react-fullstack:4.10.2021.17.37.4"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
