version: "3.8"
services:
  backend:
    image: "ksaikishore/springboot-react-fullstack:4.10.2021.18.22.2"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
